server:
  port: 8080

event-center:
  open: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:event_center
    username: root
    password: root
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
